### ISSUE TITLE
Unable to open folder if the filename have a comma ","

### ISSUE THREAD

**Issue by nalllen** [Luffier/ladderr#10]
If the downloaded file have a comma symbol in the name its not possible to right click -> open destination/containing folder
it instead opens the C:\Users\username\ folder

**Example**

ubuntu-24.04-desktop-amd64.iso **Works**
ubu,ntu-24.04-desktop-amd64.iso **Doesn't work**
ubu, ntu-24.04-desktop-amd64.iso **Doesn't work**

____

**My settings**
OS Name	Microsoft Windows 11 Pro
Version	10.0.22631 Build 22631

qBittorrent v4.6.5 Web UI (64-bit)

**Ladderr Settings Menu**
Remote path: /data/
Local path: W:\

**Qbittorent Downloads Settings**
Default Save Path: /data/torrents

**Unraid / Docker settings**
Container Path: /data/torrents
Host Path: /mnt/user/data/torrents/

**Comment by Luffier** [comment]
Should be fixed with version 0.5.2 👏.
