### ISSUE TITLE
Can open file but not open containing folder

### ISSUE THREAD

**Issue by nalllen** [Luffier/ladderr#12]
**Edit:** Noticed some inconsistencies with my problem.
 On my first instance of Qbittorent everything is working fine and i don't have the problems described here, but on the second instance with a slight different path setup i have the problems described bellow.
 
 Using Right click -> Open works just fine so cant figure out why opening folder is having problems
 
---------

Noticed some problems with opening containing folder.
v0.5.4 both ladderr.js and ladderr.reg

Two scenarios:
 
**ubuntu-24.04-desktop-amd64.iso**

Content layout set to Original when adding the torrent. No sub folders are created.

**ubuntu-22.04.4-desktop-amd64.iso**

Content layout set to Create subfolders when adding the torrent. puts the iso in a folder called ubuntu-22.04.4-desktop-amd64

______

**ubuntu-24.04-desktop-amd64.iso**

Download the file ubuntu-24.04-desktop-amd64.iso with Content layout set to original
It will be downloaded to /data/torrents/test-test/ubuntu-24.04-desktop-amd64.iso

**Works**
Content-> Right click .iso -> Open         
Windows mounts the iso file and the virtual dvd-rom folder is opened

**Not working**
 Content -> Right click .iso -> Open containing folder
 *Nothing happens*
 
 Right click torrent -> Open destination folder
*Nothing happens*
 
 
Save Path: /data/torrents/test-test
Content: ubuntu-24.04-desktop-amd64.iso

-------------------------------

**ubuntu-22.04.4-desktop-amd64.iso**

I will be downloaded to /data/torrents/test-test/ubuntu-22.04.4-desktop-amd64/ubuntu-22.04.4-desktop-amd64.iso

**Works**
Content-> Right click .iso -> Open         
Windows mounts the iso file and the virtual dvd-rom folder is opened

Right click torrent -> Open destination folder
Opens the folder S:\torrents\test-test\ubuntu-22.04.4-desktop-amd64

**Not working**
 Content -> Right click .iso -> Open containing folder
 *Nothing happens*
 
 Content -> Right click folder -> Open containing folder
 *Nothing happens*

Save Path: /data/torrents/test-test

Content: 
*Folder* ubuntu-22.04.4-desktop-amd64
ubuntu-24.04-desktop-amd64.iso

**Ladder Settings Menu**
**Remote path**/data/torrents/
**Local path** S:\torrents\

-------------------------

# Settings for working Qbittorent instance

In this instance i don't have any of the problems above and can open files by Content -> Right click .iso -> Open containing folder

**Unraid**
Host Path: /mnt/user/data/torrents/
Container Path: /data/torrents

**Windows**
Map network drive
W:\

real location 
\\unraid\data

Torrent location example
W:\torrents
\\unraid\data\torrents

**Ladder Settings Menu**
**Remote path**/data/torrents/
**Local path** W:\torrents\

# **Settings for not working Qbittorent instance**

This instance of qbittorent have the problem posted above

**Unraid**
Host Path: /mnt/user/data2/data/torrents/
Container Path: /data/torrents

**Windows**
Map network drive
S:\

real location 
\\unraid\data2\data

Torrent location example
S:\torrents
\\unraid\data2\data\torrents

**Ladder Settings Menu**
Remote path/data/torrents/
Local path S:\torrents\

**Comment by Luffier** [comment]
Thanks for the detail description. Are you using a Chromium-base browser (like Chrome)? If so, can you try the following version:

https://github.com/Luffier/ladderr/blob/chromium-first-time-fix/ladderr.js

I suspect it may be a permission problem with Chromium-base browsers, I actually encountered the same bug (opening files works but opening folders doesn't). You should get a popup warning you about permission, if you check the always trust this domain checkbox, it should never appear again and work every time.

**Comment by Luffier** [comment]
There should be two, `ladder-open` and `ladder-select`:

![image](https://github.com/Luffier/ladderr/assets/7539849/1c61ad6e-7a40-4588-90d8-ec2e5665664d)

At least I can now reproduce the problem, I should have a fix soon. In the meantime, you can force it to ask for permission by running the following in the console:

```js
window.open('ladderr-select:')
```

**Comment by Luffier** [comment]
Should be fixed with version 0.5.5 😌.
