### ISSUE TITLE
PopUp "Open Console Windows Host"

### ISSUE THREAD

**Issue by mikokwan** [Luffier/ladderr#14]
Thanks for fixing the 5.0 issue with 0.5.6 version. Is there any way can avoid the popup "Open Console Windows Host" everytime?

**Comment by Luffier** [comment]
You are using a Chromium-based browser and your qBittorrent instance is using HTTP right? The solution is to start using HTTPS (or move to Firefox). For HTTPS in a local server you could use something like [mkcert](https://github.com/FiloSottile/mkcert).
