### ISSUE TITLE
Ladderr not working with qBittorrent v5.1.0 betas

### ISSUE THREAD

**Issue by bachig26** [Luffier/ladderr#16]
I'm using the latest beta v5.1.0 of qBittorrent setup with libtorrent-2.0.10 from [master branch](https://github.com/qbittorrent/qBittorrent/actions/runs/11324150220) and I can't see the `Ladderr Options` in the `Tools` menu or anywhere in qBittorrent.

@Luffier can please have look into this issue and I'm hoping to see an hot fix update if possible. Cheers!

**Comment by Luffier** [comment]
I can't replicate it. I can see the menu in that version. Can you make sure the script is loading correctly, what does the dev console say?

**Comment by bachig26** [comment]
> I can't replicate it. I can see the menu in that version. Can you make sure the script is loading correctly, what does the dev console say?

It works fine now, I think I made mistake with the installation..not sure, but works well now.
