### ISSUE TITLE
Multiple Windows Explorer processes in task manager

### ISSUE THREAD

**Issue by nalllen** [Luffier/ladderr#17]
If you open a folder or destination a new "Windows Explorer" processes is created instead of opening under the original Windows Explorer that's always running, that might not be a issue but after closing the window the processe is still in the Task manager.

Here is a short video of the task manager
Sec 2: opened the first destination/folder
Sec 6: opened the second destination/folder
Sec 7: Closed the two folders

https://github.com/user-attachments/assets/dc7d61a0-3394-4ea4-a29f-b8a11c42eacd

Edit: Using end task in the task manager work fine

**Comment by Luffier** [comment]
Yes, this is a problem with Windows and `explorer.exe`. It only happens with folders, with files it culls the process after a while.

One can replicate it by executing the following command `Start-Process explorer.exe C:\`.

I tried many things when the script used Python, but couldn't find a solution, now that the script uses Poweshell maybe something can be done. Right now my time is limited so I can't promise a quick fix.

**Comment by TobbeLino** [comment]
My system (Windows 11 Pro, 24H2) seems to check/garbage collect orphan explorer.exe processes once every 1 minute.

If I run `Start-Process explorer.exe C:\` and close the window again, the explorer process will be moved down to "Windows processes" in task manager when closed. And it will disappear entirely from task manager exactly 1 minute after it was opened.

And if I keep the explorer window open for 1 min 30 sec and then close it, the process will be flushed exactly 2 minutes after it was opened (i.e. 30 seconds after closed). So this does not seem to be an issue (anymore?)

**Comment by Luffier** [comment]
@TobbeLino Still on 23H2, will test as soon as I get the 24H2 update.

**Comment by Luffier** [comment]
Got the update and can confirm this issue is fixed in 24H2 👌.
