### ISSUE TITLE
Unable to open folder if multiple folders in save path

### ISSUE THREAD

**Issue by nalllen** [Luffier/ladderr#9]
Gonna start of by saying thanks for makings this, wished qbit would have had this function for years now ❤️  

I'm not particularly used to writing issues on github but ill try to explain it as simple as i can.

**Issue**

If the save path is more than one folder deep opening a file or containing folder doesn't work, either nothing happens or the user folder opens, in my case C:\Users\username\OneDrive since i have onedrive installed.

**Example**

Download ubuntu-24.04-desktop-amd64.iso from

https://ubuntu.com/download/alternative-downloads

Save Path: /data/torrents/test/
Open destination folder works

/data/torrents/test/other/
Open destination folder doesn't work

____

**My settings**
OS Name	Microsoft Windows 11 Pro
Version	10.0.22631 Build 22631
qBittorrent v4.6.5 Web UI (64-bit)

**Ladderr Settings Menu**
Remote path: /data/
Local path: W:\

*adding torrent after the slash makes /data/torrents/test/other/ work but not /data/torrents/test/other/newfolder/ so the same depth problem*

**Qbittorent Downloads Settings**
Default Save Path: /data/torrents

**Unraid / Docker settings**
Container Path: /data/torrents
Host Path: /mnt/user/data/torrents/

**Comment by Luffier** [comment]
Thank you for opening this issue, it should be fixed with version 0.5.1. Greasyfork is giving me problems and the autoupdate doesn't always work, you can update through openuserjs in the meantime.
